"use client";

/**
 * McpTokensModal — "Connect your AI tools".
 *
 * Pick your client → get an accurate, per-client instruction (MCP config +
 * auto-capture hook + verification) generated by lib/mcp-adapters. Nothing is
 * hardcoded across tools; every tool's real schema comes from its own adapter,
 * and we never claim auto-capture works until the user verifies it.
 *
 * Origin-aware (localhost dev vs prod). The freshly-minted token is embedded,
 * shown once.
 */
import { useEffect, useMemo, useState } from "react";
import { useI18n } from "./i18n";
import { buildAdapter, buildInstruction, verificationSteps, ADAPTER_IDS, type AdapterId } from "@/lib/mcp-adapters";

interface TokenRow {
  tokenHash: string;
  label: string;
  createdAt: string;
  lastUsedAt: string | null;
}

export function McpTokensModal({ onClose }: { onClose: () => void }) {
  const { language } = useI18n();
  const zh = language === "zh";
  const [tokens, setTokens] = useState<TokenRow[]>([]);
  const [label, setLabel] = useState("");
  const [fresh, setFresh] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const [tool, setTool] = useState<AdapterId>("claude-code");
  const [showRaw, setShowRaw] = useState(false);

  const origin = typeof window !== "undefined" ? window.location.origin : "https://synapse.cjlin.com";
  const token = fresh ?? "syn_YOUR_TOKEN";

  const adapter = useMemo(
    () => buildAdapter(tool, { mcpUrl: `${origin}/api/mcp`, hookUrl: `${origin}/api/hook`, token }),
    [tool, origin, token],
  );
  const instruction = useMemo(() => buildInstruction(adapter, zh), [adapter, zh]);
  const steps = useMemo(() => verificationSteps(adapter), [adapter]);

  useEffect(() => {
    fetch("/api/tokens").then((r) => r.json()).then((j) => setTokens(j.tokens ?? [])).catch(() => {});
  }, []);

  async function create() {
    if (busy) return;
    setBusy(true);
    try {
      const r = await fetch("/api/tokens", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ label: label.trim() || "my-tool" }),
      });
      const j = await r.json();
      if (j.token) { setFresh(j.token); setTokens(j.tokens ?? []); setLabel(""); }
    } finally { setBusy(false); }
  }

  async function revoke(tokenHash: string) {
    const r = await fetch("/api/tokens", {
      method: "DELETE", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tokenHash }),
    });
    const j = await r.json();
    setTokens(j.tokens ?? []);
  }

  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text).then(() => { setCopied(key); setTimeout(() => setCopied(null), 1400); });
  }

  const toolLabel: Record<AdapterId, string> = {
    "claude-code": "Claude Code", codex: "Codex", cursor: "Cursor", generic: zh ? "其他工具" : "Other",
  };
  const autoBadge = adapter.supportsAutoCapture === "yes"
    ? { txt: zh ? "支持自动捕获" : "auto-capture", color: "#2E7D32", bg: "rgba(46,125,50,0.1)" }
    : adapter.supportsAutoCapture === "no"
      ? { txt: zh ? "不支持自动捕获" : "no auto-capture", color: "#B3382C", bg: "rgba(179,56,44,0.08)" }
      : { txt: zh ? "自动捕获需你的工具支持钩子" : "auto-capture if hooks supported", color: "#B3651A", bg: "var(--insight)" };

  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, zIndex: 300, background: "rgba(20,20,18,0.42)", display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}>
      <section onClick={(e) => e.stopPropagation()} style={{ width: "min(700px, 100%)", maxHeight: "88vh", overflowY: "auto", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 14, boxShadow: "0 24px 60px rgba(0,0,0,0.24)" }}>
        <header style={{ padding: "16px 20px 12px", borderBottom: "1px solid var(--border)", display: "flex", justifyContent: "space-between", gap: 16 }}>
          <div>
            <h2 style={{ fontSize: 17, margin: 0, color: "var(--text)" }}>{zh ? "连接你的 AI 工具" : "Connect your AI tools"}</h2>
            <p style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 4, lineHeight: 1.5 }}>
              {zh ? "生成令牌,选你的工具,把生成的指令粘给它——它按自己的正确配置方式接入,并要你验证后才算成功。"
                  : "Generate a token, pick your tool, paste the instruction to it — it configures itself correctly and only counts as done after you verify."}
            </p>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none", color: "var(--text-muted)", fontSize: 18, cursor: "pointer", height: 24 }}>✕</button>
        </header>

        <div style={{ padding: "14px 20px 20px", display: "flex", flexDirection: "column", gap: 16 }}>
          {/* Step 1: mint */}
          <div>
            <StepLabel n={1} text={zh ? "生成一个访问令牌" : "Generate an access token"} />
            <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
              <input value={label} onChange={(e) => setLabel(e.target.value)}
                placeholder={zh ? "备注,如 MacBook Codex" : "Label, e.g. MacBook Codex"}
                style={{ flex: 1, padding: "9px 12px", borderRadius: 9, border: "1px solid var(--border)", background: "var(--bg)", color: "var(--text)", fontSize: 13 }} />
              <button onClick={create} disabled={busy}
                style={{ padding: "9px 16px", borderRadius: 9, border: "none", background: "var(--accent)", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer", opacity: busy ? 0.6 : 1 }}>
                {zh ? "生成" : "Generate"}
              </button>
            </div>
            {fresh && (
              <div style={{ fontSize: 11.5, color: "#B3651A", background: "var(--insight)", border: "1px solid var(--insight-border)", borderRadius: 8, padding: "7px 10px", marginTop: 8 }}>
                {zh ? "⚠️ 令牌只显示这一次,已嵌进下面的指令,复制走即可。" : "⚠️ Shown once — it's embedded in the instruction below. Copy now."}
              </div>
            )}
          </div>

          {/* Step 2: pick tool + instruction */}
          <div style={{ opacity: fresh ? 1 : 0.5, pointerEvents: fresh ? "auto" : "none" }}>
            <StepLabel n={2} text={zh ? "选择你的工具" : "Pick your tool"} />
            <div style={{ display: "flex", gap: 6, marginTop: 8, flexWrap: "wrap" }}>
              {ADAPTER_IDS.map((id) => (
                <button key={id} onClick={() => setTool(id)}
                  style={{
                    padding: "6px 12px", borderRadius: 8, fontSize: 12.5, fontWeight: 600, cursor: "pointer",
                    border: tool === id ? "1px solid var(--accent)" : "1px solid var(--border)",
                    background: tool === id ? "var(--accent)" : "transparent",
                    color: tool === id ? "#fff" : "var(--text)",
                  }}>{toolLabel[id]}</button>
              ))}
            </div>

            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}>
              <span style={{ fontSize: 12.5, fontWeight: 700, color: "var(--text)" }}>
                {zh ? "把这段粘给 " : "Paste this into "}{toolLabel[tool]}
              </span>
              <span style={{ display: "flex", gap: 8, alignItems: "center" }}>
                <span style={{ fontSize: 10.5, fontWeight: 700, color: autoBadge.color, background: autoBadge.bg, borderRadius: 6, padding: "2px 8px" }}>{autoBadge.txt}</span>
                <button onClick={() => copy(instruction, "inst")} style={copyBtnStyle}>{copied === "inst" ? (zh ? "已复制 ✓" : "Copied ✓") : (zh ? "复制指令" : "Copy")}</button>
              </span>
            </div>
            <pre style={{ margin: "8px 0 0", padding: "12px 14px", fontSize: 12, lineHeight: 1.6, whiteSpace: "pre-wrap", wordBreak: "break-word", background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: 10, color: "var(--text)", maxHeight: 300, overflowY: "auto" }}>{instruction}</pre>

            {/* Raw snippets + verification */}
            <button onClick={() => setShowRaw((v) => !v)} style={{ background: "none", border: "none", color: "var(--text-muted)", fontSize: 12.5, cursor: "pointer", padding: "10px 0 0" }}>
              {showRaw ? "▾ " : "▸ "}{zh ? "单独复制各段 + 验证步骤" : "Copy pieces individually + verification"}
            </button>
            {showRaw && (
              <div style={{ display: "flex", flexDirection: "column", gap: 10, marginTop: 8 }}>
                <Snippet title={`MCP · ${adapter.mcpConfig.where}`} body={adapter.mcpConfig.snippet} k="mcp" copied={copied} copy={copy} zh={zh} />
                {adapter.hookConfig ? (
                  <>
                    <Snippet title={zh ? "① 下载 hook 脚本" : "① Download hook script"} body={adapter.hookDownload} k="dl" copied={copied} copy={copy} zh={zh} />
                    <Snippet title={`② hook · ${adapter.hookConfig.where}`} body={adapter.hookConfig.snippet} note={adapter.hookConfig.note} k="hk" copied={copied} copy={copy} zh={zh} />
                  </>
                ) : (
                  <div style={{ fontSize: 12, color: "var(--text-muted)", border: "1px dashed var(--border)", borderRadius: 8, padding: "8px 12px", lineHeight: 1.5 }}>
                    {adapter.fallback}
                  </div>
                )}
                <div style={{ border: "1px solid var(--border)", borderRadius: 10, padding: "10px 12px" }}>
                  <div style={{ fontSize: 12, fontWeight: 700, marginBottom: 6 }}>{zh ? "验证步骤" : "Verification"}</div>
                  <ol style={{ margin: 0, paddingLeft: 18, fontSize: 12, lineHeight: 1.6, color: "var(--text)" }}>
                    {steps.map((s, i) => <li key={i}>{s}</li>)}
                  </ol>
                </div>
              </div>
            )}
          </div>

          {/* Active tokens */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text-muted)", letterSpacing: 0.5, marginBottom: 8 }}>
              {zh ? `已有令牌(${tokens.length})` : `Active tokens (${tokens.length})`}
            </div>
            {tokens.length === 0 ? (
              <div style={{ fontSize: 12.5, color: "var(--text-muted)" }}>{zh ? "还没有令牌。" : "No tokens yet."}</div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                {tokens.map((tk) => (
                  <div key={tk.tokenHash} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 12px", borderRadius: 9, border: "1px solid var(--border)", fontSize: 12.5 }}>
                    <span style={{ flex: 1, minWidth: 0 }}>
                      <span style={{ fontWeight: 700 }}>{tk.label || "(no label)"}</span>
                      <span style={{ color: "var(--text-muted)", marginLeft: 8 }}>
                        {(zh ? "创建于 " : "created ") + tk.createdAt.slice(0, 10)}
                        {tk.lastUsedAt ? ` · ${zh ? "最近使用 " : "last used "}${tk.lastUsedAt.slice(0, 10)}` : ""}
                      </span>
                    </span>
                    <button onClick={() => revoke(tk.tokenHash)} style={{ background: "none", border: "1px solid var(--border)", borderRadius: 7, padding: "4px 10px", fontSize: 12, color: "#B3382C", cursor: "pointer" }}>
                      {zh ? "撤销" : "Revoke"}
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}

function Snippet({ title, body, note, k, copied, copy, zh }: {
  title: string; body: string; note?: string; k: string;
  copied: string | null; copy: (t: string, k: string) => void; zh: boolean;
}) {
  return (
    <div style={{ border: "1px solid var(--border)", borderRadius: 10, overflow: "hidden" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "7px 12px", background: "var(--surface-2)", fontSize: 12, fontWeight: 700 }}>
        <span style={{ minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{title}</span>
        <button onClick={() => copy(body, k)} style={copyBtnStyle}>{copied === k ? "✓" : (zh ? "复制" : "Copy")}</button>
      </div>
      <pre style={{ margin: 0, padding: "10px 12px", fontSize: 11.5, lineHeight: 1.55, whiteSpace: "pre-wrap", wordBreak: "break-word", color: "var(--text)" }}>{body}</pre>
      {note && <div style={{ padding: "0 12px 10px", fontSize: 11, color: "var(--text-muted)", lineHeight: 1.5 }}>{note}</div>}
    </div>
  );
}

function StepLabel({ n, text }: { n: number; text: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
      <span style={{ width: 20, height: 20, borderRadius: "50%", background: "var(--accent)", color: "#fff", fontSize: 12, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center" }}>{n}</span>
      <span style={{ fontSize: 13, fontWeight: 700, color: "var(--text)" }}>{text}</span>
    </div>
  );
}

const copyBtnStyle: React.CSSProperties = {
  background: "none", border: "1px solid var(--border)", borderRadius: 7,
  padding: "3px 10px", fontSize: 11.5, color: "var(--text)", cursor: "pointer", flexShrink: 0,
};
